### ISSUE TITLE
Inviting players

### ISSUE THREAD

**Issue by tejaswini4** [jtaugust/cs414-f18-001-JavatheHutt#18]
- Select (multiple) users to send invites to.
- Send notifications to the selected users

**Comment by jwelch31** [comment]
option 1:
invite as many people to a single game, first come first serve (will we delete notifications if someone accepts, make people click on the notification only to find out the game is full)

option 2:
invite as many people to a game, if they respond yes a new game will be created for every acceptance (not a first come first serve, only creates if the player agrees)
